[package]
name = "n00n-semble"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
n00n-search = { workspace = true }
thiserror = { workspace = true }
tempfile = { workspace = true }
