use crate::gen_lua_api;

const NAME: &str = "maki-plugin-dev";
const DESCRIPTION: &str = "Write or modify maki plugins or init.lua config in Lua: custom tools, slash commands, keymaps, UI. Authoring guide, real example, indexed maki Lua API reference. Load before any maki plugin work.";
const REFERENCE_PLACEHOLDER: &str = "__MAKI_REFERENCE_PATH__";

const EXAMPLE: &str = include_str!("../../plugins/glob/init.lua");

const GUIDE: &str = r#"# Writing maki plugins

Maki plugins are plain Lua files (Luau) that run inside maki. A plugin can
register tools the LLM calls, slash commands, keymaps, prompt hints, and
custom UI. Everything lives under the global `maki` table. An index of the
full API reference is at the end of this document.

## Where plugin code goes

- `~/.config/maki/init.lua` - global, loaded for every project
- `<project>/.maki/init.lua` - project-local

Either file can call `maki.setup({ ... })` for configuration and register
tools or commands. There are no separate plugin directories yet.

## Development loop

You cannot run slash commands or restart maki. After editing, ask the user
to run `/reload` (rebuilds plugins and config in place). Until then your
changes are not live. If a backtrace comes out useless, suggest restarting
with `--no-jit`.

To debug, add `maki.log.info|warn|error(...)` calls. They write to `maki.log`
in the dir `maki.env.logs_dir()` returns (Linux: `~/.local/logs/maki/`).
Read that file yourself after the user reloads and reproduces.

## Conventions

- Fallible runtime calls return a `(value, err)` pair; check `err` before using `value`.
- Tool handlers report failures with `{ llm_output = "error: ...", is_error = true }`, not by raising.
- The model picks tools by reading `description`, so state precisely what the tool does and when to use it.
- Reusable helpers ship with maki; see "Shared helper modules" in the reference file.

## A complete real example

The bundled `glob` tool, verbatim: options registration, schema, header and
restore hooks, error handling, LLM output truncation, collapsible UI view:

```lua
"#;

/// Emit {content} as a Lua long-bracket string literal. The forced trailing
/// newline keeps content away from the closing delimiter, so scanning for
/// `]=]`-style brackets inside the content picks a safe level. Lua strips the
/// first newline after the opening bracket, so the content survives exactly.
fn lua_long_string(content: &str) -> String {
    let newline = if content.ends_with('\n') { "" } else { "\n" };
    let eq = (0..)
        .map(|n| "=".repeat(n))
        .find(|eq| !content.contains(&format!("]{eq}]")))
        .expect("unbounded range");
    format!("[{eq}[\n{content}{newline}]{eq}]")
}

/// Returns the skill module and the reference module. The skill carries the
/// guide, example, and a line-numbered index; the skill plugin writes the
/// full reference to disk so the model reads only the sections it needs.
pub fn generate() -> (String, String) {
    let reference = gen_lua_api::reference();
    let content = format!(
        "{GUIDE}{EXAMPLE}```\n\n# Full API reference\n\n\
         The complete Lua API reference - every function with parameters, return\n\
         values, and examples, plus shared helper module sources - is on disk at:\n\n\
         `{REFERENCE_PLACEHOLDER}`\n\n\
         The index below maps every function to its line in that file. Before using\n\
         a function you are not certain about, read its section (read tool with\n\
         offset = line number) or grep the file for its name. Never guess a\n\
         signature or parameter table from the index alone.\n\n\
         Signatures use Neovim notation: `{{path}}` is required, `{{opts?}}` is\n\
         optional, `{{...}}` is variadic.\n{}",
        gen_lua_api::reference_index(&reference)
    );
    // {:?} escapes are valid Lua for these ASCII consts; spec.lua loads the output in CI.
    let skill = format!(
        "-- Generated by maki-docgen. Do not edit; run `just gen-docs`.\nreturn {{\n  name = {NAME:?},\n  description = {DESCRIPTION:?},\n  reference_placeholder = {REFERENCE_PLACEHOLDER:?},\n  content = {},\n}}\n",
        lua_long_string(&content)
    );
    let reference_module = format!(
        "-- Generated by maki-docgen. Do not edit; run `just gen-docs`.\nreturn {{\n  content = {},\n}}\n",
        lua_long_string(&reference)
    );
    (skill, reference_module)
}

#[cfg(test)]
mod tests {
    use super::lua_long_string;
    use test_case::test_case;

    #[test_case("no brackets\n", "[[\nno brackets\n]]"; "plain text level zero")]
    #[test_case("a ]] b\n", "[=[\na ]] b\n]=]"; "closing level zero taken")]
    #[test_case("a ]] b ]=] c\n", "[==[\na ]] b ]=] c\n]==]"; "levels zero and one taken")]
    #[test_case("ends with bracket eq ]=", "[[\nends with bracket eq ]=\n]]"; "delimiter prefix suffix gets newline")]
    #[test_case("no trailing newline", "[[\nno trailing newline\n]]"; "trailing newline added")]
    fn long_string_is_safe(content: &str, expected: &str) {
        assert_eq!(lua_long_string(content), expected);
    }
}
