pub(crate) const MODELS: &[crate::model::ModelEntry] = &[
    crate::model::ModelEntry {
        prefixes: &["auto"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.25,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.3-codex-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["composer-2.5"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: true,
        pricing: crate::model::ModelPricing {
            input: 0.5,
            output: 2.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-thinking-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-thinking-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["cursor-grok-4.5-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["composer-2.5-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.5,
            output: 2.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-5-thinking-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-8-thinking-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-none"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-none-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-sol-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-none"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-none-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-extra-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.5-extra-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 30.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-thinking-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-thinking-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-fable-5-thinking-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 10.0,
            output: 50.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-thinking-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-thinking-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-thinking-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-thinking-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-sonnet-5-thinking-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-none"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-none-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-low"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-low-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-medium"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-medium-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-high"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-high-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-xhigh"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-xhigh-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-max"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-terra-max-fast"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-sonnet-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 6.0,
            output: 22.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-sonnet-medium-thinking"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 6.0,
            output: 22.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-opus-4-7-thinking-max-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-medium"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-medium-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.5,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-opus-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-opus-max"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-opus-high-thinking"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.6-opus-max-thinking"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.5-opus-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.5-opus-high-thinking"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 5.0,
            output: 25.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-low"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-low-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-high"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-high-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-xhigh"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.2-xhigh-fast"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.75,
            output: 14.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 272_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-none"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-none-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-low"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-low-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-medium"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-medium-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-high"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-high-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-xhigh"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-xhigh-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-max"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.6-luna-max-fast"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.0,
            output: 6.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.6-flash-minimal"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.5,
            output: 7.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.6-flash-low"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.5,
            output: 7.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.6-flash-medium"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.5,
            output: 7.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.6-flash-high"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.5,
            output: 7.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.1-pro"],
        tier: crate::model::ModelTier::Strong,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 2.0,
            output: 12.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-mini-none"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.75,
            output: 4.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-mini-low"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.75,
            output: 4.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-mini-medium"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.75,
            output: 4.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-mini-high"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.75,
            output: 4.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-mini-xhigh"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.75,
            output: 4.5,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-nano-none"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.2,
            output: 1.25,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-nano-low"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.2,
            output: 1.25,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-nano-medium"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.2,
            output: 1.25,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-nano-high"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.2,
            output: 1.25,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.4-nano-xhigh"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.2,
            output: 1.25,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.5-sonnet"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4.5-sonnet-thinking"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.1-low"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.25,
            output: 10.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.1"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: true,
        pricing: crate::model::ModelPricing {
            input: 1.25,
            output: 10.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5.1-high"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.25,
            output: 10.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3-flash"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: true,
        pricing: crate::model::ModelPricing {
            input: 0.5,
            output: 3.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gemini-3.5-flash"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Gemini,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.5,
            output: 9.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 128_000,
        context_window: 1_000_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4-sonnet"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["claude-4-sonnet-thinking"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Claude,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 3.0,
            output: 15.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["gpt-5-mini"],
        tier: crate::model::ModelTier::Weak,
        family: crate::model::ModelFamily::Gpt,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.25,
            output: 2.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["kimi-k2.7-code"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Generic,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 0.95,
            output: 4.0,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 200_000,
    },
    crate::model::ModelEntry {
        prefixes: &["glm-5.2-high"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Glm,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.4,
            output: 4.4,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
    crate::model::ModelEntry {
        prefixes: &["glm-5.2-max"],
        tier: crate::model::ModelTier::Medium,
        family: crate::model::ModelFamily::Glm,
        vision: false,
        default: false,
        pricing: crate::model::ModelPricing {
            input: 1.4,
            output: 4.4,
            cache_write: 0.0,
            cache_read: 0.0,
            fast: None,
        },
        max_output_tokens: 32_768,
        context_window: 128_000,
    },
];
