use crate::model::{ModelEntry, ModelFamily, ModelPricing, ModelTier};

#[allow(clippy::too_many_lines)]
pub(crate) const fn models() -> &'static [ModelEntry] {
    &[
        ModelEntry {
            prefixes: &["claude-opus-5-medium", "opus"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-max"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-low-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-medium-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-high-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-xhigh-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-5-max-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-5-fable-medium"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-5-fable-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-5-fable-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-5-fable-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-5-fable-max"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-5-medium", "claude", "sonnet"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-5-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-5-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-5-xhigh"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-5-max"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-medium"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-none"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-max"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-none-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 60.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-low-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 60.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-medium-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 60.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-high-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 60.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-sol-xhigh-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 60.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-none"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-low"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-xhigh"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-max"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-none-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-low-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-medium-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-high-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-luna-xhigh-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.00,
                output: 0.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2-max"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.70,
                output: 2.20,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2-1m"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.70,
                output: 2.20,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2-max-1m"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.70,
                output: 2.20,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2-none"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.70,
                output: 2.20,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["glm-5-2-none-1m"],
            tier: ModelTier::Weak,
            family: ModelFamily::Glm,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.70,
                output: 2.20,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["kimi-k3-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["kimi-k3-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["kimi-k3-max"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["swe-1-7-max", "swe-1-7", "swe-1.7", "swe-1.7-max"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: true,
            pricing: ModelPricing {
                input: 0.00,
                output: 0.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 262_144,
        },
        ModelEntry {
            prefixes: &["swe-1-7-medium", "swe-1.7-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.00,
                output: 0.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 262_144,
        },
        ModelEntry {
            prefixes: &["swe-1-7-lightning", "swe-1.7-lightning", "swe"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 12.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 96_000,
            context_window: 202_752,
        },
        ModelEntry {
            prefixes: &["adaptive"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.50,
                output: 2.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-7-medium"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-7-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-7-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-7-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-7-max"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-medium"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-max"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-low-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-medium-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-high-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-xhigh-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-8-max-fast"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 10.00,
                output: 50.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gemini-3-5-flash-minimal"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 9.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-5-flash-low"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 9.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-5-flash-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 9.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-5-flash-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 9.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-6-flash-minimal", "gemini"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 7.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-6-flash-low"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 7.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-6-flash-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 7.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-6-flash-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.50,
                output: 7.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-none", "gpt"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-medium"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-xhigh"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-max"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-none-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-low-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-medium-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-high-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-6-terra-xhigh-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["grok-4-5-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 100_000,
            context_window: 500_000,
        },
        ModelEntry {
            prefixes: &["grok-4-5-medium"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 100_000,
            context_window: 500_000,
        },
        ModelEntry {
            prefixes: &["grok-4-5-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 6.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 100_000,
            context_window: 500_000,
        },
        ModelEntry {
            prefixes: &["inkling-none"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["inkling-low"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["inkling-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["inkling-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["inkling-xhigh"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["inkling-max"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.40,
                output: 4.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 131_072,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-6"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-6-thinking"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-6-1m"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-opus-4-6-thinking-1m"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-none"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-medium"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-xhigh"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.50,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-none-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-low-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-medium-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-high-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-xhigh-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-none"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-low"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-medium"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-high"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-xhigh"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 30.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-none-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 12.50,
                output: 75.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-low-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 12.50,
                output: 75.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-medium-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 12.50,
                output: 75.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-high-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 12.50,
                output: 75.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-5-xhigh-priority"],
            tier: ModelTier::Strong,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 12.50,
                output: 75.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 272_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-mini-low"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.75,
                output: 4.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-mini-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.75,
                output: 4.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-mini-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.75,
                output: 4.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-4-mini-xhigh"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.75,
                output: 4.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-4-6"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-4-6-thinking"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-4-6-1m"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["claude-sonnet-4-6-thinking-1m"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 1_000_000,
        },
        ModelEntry {
            prefixes: &["MODEL_GPT_5_2_LOW"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_GPT_5_2_MEDIUM"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_GPT_5_2_NONE"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_GPT_5_2_HIGH"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_GPT_5_2_XHIGH"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_CLAUDE_4_5_OPUS"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 64_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["MODEL_CLAUDE_4_5_OPUS_THINKING"],
            tier: ModelTier::Strong,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 5.00,
                output: 25.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 64_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_11", "haiku"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.00,
                output: 5.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 64_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_2"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 64_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_3"],
            tier: ModelTier::Medium,
            family: ModelFamily::Claude,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.00,
                output: 15.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 64_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["MODEL_CHAT_GPT_4_1_2025_04_14"],
            tier: ModelTier::Medium,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 8.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 32_768,
            context_window: 1_047_576,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_12"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.25,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_13"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.25,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_14"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.25,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["MODEL_PRIVATE_15"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.25,
                output: 10.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 384_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-low", "codex"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-medium"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-high"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-xhigh"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.75,
                output: 14.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-low-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.50,
                output: 28.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-medium-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.50,
                output: 28.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-high-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.50,
                output: 28.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["gpt-5-3-codex-xhigh-priority"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gpt,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 3.50,
                output: 28.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 400_000,
        },
        ModelEntry {
            prefixes: &["kimi-k2-6"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.95,
                output: 4.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 8_192,
            context_window: 262_144,
        },
        ModelEntry {
            prefixes: &["kimi-k2-7"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.95,
                output: 4.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 16_000,
            context_window: 262_144,
        },
        ModelEntry {
            prefixes: &["nemotron-3-ultra-nvfp4"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.60,
                output: 2.40,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 32_768,
            context_window: 262_144,
        },
        ModelEntry {
            prefixes: &["swe-1-6"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.00,
                output: 0.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["swe-1-6-fast"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.30,
                output: 1.50,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 128_000,
            context_window: 200_000,
        },
        ModelEntry {
            prefixes: &["gemini-3-1-pro-low"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["gemini-3-1-pro-high"],
            tier: ModelTier::Medium,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 2.00,
                output: 12.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["MODEL_GOOGLE_GEMINI_3_0_FLASH_MINIMAL"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.50,
                output: 3.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["MODEL_GOOGLE_GEMINI_3_0_FLASH_LOW"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.50,
                output: 3.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["MODEL_GOOGLE_GEMINI_3_0_FLASH_MEDIUM"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.50,
                output: 3.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["MODEL_GOOGLE_GEMINI_3_0_FLASH_HIGH"],
            tier: ModelTier::Weak,
            family: ModelFamily::Gemini,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 0.50,
                output: 3.00,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 65_535,
            context_window: 1_048_576,
        },
        ModelEntry {
            prefixes: &["deepseek-v4"],
            tier: ModelTier::Weak,
            family: ModelFamily::Generic,
            vision: true,
            default: false,
            pricing: ModelPricing {
                input: 1.74,
                output: 3.48,
                cache_write: 0.00,
                cache_read: 0.00,
                fast: None,
            },
            max_output_tokens: 384_000,
            context_window: 1_048_576,
        },
    ]
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use test_case::test_case;

    use super::models;
    use crate::model::lookup_entry;

    #[test]
    fn catalog_prefixes_are_unique() {
        let mut prefixes = HashSet::new();

        for prefix in models().iter().flat_map(|entry| entry.prefixes) {
            assert!(
                prefixes.insert(prefix),
                "duplicate Devin model prefix: {prefix}"
            );
        }
    }

    #[test_case("opus", "claude-opus-5-medium" ; "opus")]
    #[test_case("sonnet", "claude-sonnet-5-medium" ; "sonnet")]
    #[test_case("claude", "claude-sonnet-5-medium" ; "claude")]
    #[test_case("gpt", "gpt-5-6-terra-none" ; "gpt")]
    #[test_case("gemini", "gemini-3-6-flash-minimal" ; "gemini")]
    #[test_case("haiku", "MODEL_PRIVATE_11" ; "haiku")]
    #[test_case("codex", "gpt-5-3-codex-low" ; "codex")]
    #[test_case("swe", "swe-1-7-lightning" ; "swe")]
    #[test_case("swe-1-7", "swe-1-7-max" ; "swe_1_7")]
    #[test_case("swe-1.7", "swe-1-7-max" ; "swe_1_dot_7")]
    #[test_case("swe-1-7-max", "swe-1-7-max" ; "swe_1_7_max")]
    #[test_case("swe-1.7-max", "swe-1-7-max" ; "swe_1_dot_7_max")]
    #[test_case("swe-1-7-medium", "swe-1-7-medium" ; "swe_1_7_medium")]
    #[test_case("swe-1.7-medium", "swe-1-7-medium" ; "swe_1_dot_7_medium")]
    fn catalog_alias_resolves_to_canonical_id(alias: &str, canonical_id: &str) {
        let entry = lookup_entry(models(), alias).expect("catalog alias should resolve");

        assert_eq!(entry.prefixes.first().copied(), Some(canonical_id));
    }

    #[test]
    fn catalog_max_output_does_not_exceed_context_window() {
        for entry in models() {
            assert!(
                entry.max_output_tokens <= entry.context_window,
                "{} has max output {} above context window {}",
                entry.prefixes[0],
                entry.max_output_tokens,
                entry.context_window,
            );
        }
    }
}
