name: Cargo vet

on:
  push:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**/Cargo.toml"
      - "supply-chain/**"
      - ".github/workflows/cargo-vet.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**/Cargo.toml"
      - "supply-chain/**"
      - ".github/workflows/cargo-vet.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vet:
    name: Supply chain vet
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262'  # v4
        with:
          persist-credentials: false

      - uses: 'dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772'  # master
        with:
          toolchain: nightly-2026-08-20

      - uses: 'taiki-e/install-action@a7e592b24782184db1613493a5e65d2e12199f80'  # v2.69.4
        with:
          tool: cargo-vet

      - name: Run cargo vet
        run: cargo vet
