name: Cargo geiger

on:
  push:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "src/**"
      - ".github/workflows/cargo-geiger.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "crates/**"
      - "src/**"
      - ".github/workflows/cargo-geiger.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  geiger:
    name: Unsafe usage
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262'  # v4
        with:
          persist-credentials: false

      - uses: 'Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32'  # v2
        with:
          shared-key: "linux-geiger"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - uses: 'jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea'  # v4.2.1
        with:
          install_args: 'cargo:cargo-geiger'

      - name: Run cargo geiger
        run: cargo geiger --all --offline
