name: Markdownlint

on:
  push:
    branches: ["main"]
    paths:
      - "**.md"
      - ".markdownlint.yaml"
      - ".github/workflows/markdownlint.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.md"
      - ".markdownlint.yaml"
      - ".github/workflows/markdownlint.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262'  # v4
        with:
          persist-credentials: false

      - uses: 'DavidAnson/markdownlint-cli2-action@28a7e8bdb81fd8ad675883de92c758ab78e0ce10'  # v24
        with:
          globs: |
            *.md
            site/**/*.md
            crates/**/*.md
