name: Scorecard

on:
  branch_protection_rule:
  push:
    branches: ["main"]
  schedule:
    - cron: "22 22 * * 2"
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - uses: 'actions/checkout@11d5960a326750d5838078e36cf38b85af677262'  # v4
        with:
          persist-credentials: false

      - uses: 'ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc'  # v2.4.4
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - uses: 'github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07'  # v3
        with:
          sarif_file: scorecard.sarif
