name: Typos

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.md"
      - "**/*.lua"
      - "**/*.py"
      - "**/*.toml"
      - ".github/workflows/**"
      - "typos.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.md"
      - "**/*.lua"
      - "**/*.py"
      - "**/*.toml"
      - ".github/workflows/**"
      - "typos.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1
        with:
          install_args: typos
      - run: typos
