name: YAML

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".yamllint"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1
        with:
          install_args: yamllint
      - run: yamllint .
