name: Zizmor

on:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/**"
  push:
    branches: ["main"]
    paths:
      - ".github/**"
  schedule:
    - cron: "23 6 * * 2"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  zizmor:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02  # v0.6.0
        with:
          online-audits: false
